### ISSUE TITLE
Not Spawning Troubleshooting

### ISSUE THREAD

**Issue by Visionz1** [YoshiWoof22/WEC-PvE#2]
This is me (Penguin) to answer your question I removed all the other mods that had different NPC spawns. Ie Air Traffic,PVE Threat.
Currently the only NPC mods active is:
Modular Encounters
NPC Programming Extender
WEC PvE Encounters [WIP - Alpha]

Issue I had yesterday is that they did not have any ownership. I flew around the planet and ran across some drone building factories that also did not have any ownership attached to them.

**Comment by Visionz1** [comment]
So did a little more messing around and I think it has something to do with my world because I created a new world and now they are spawning with the proper faction tag. I may just need to remove all the old factions and see if that works.

**Comment by YoshiWoof22** [comment]
@Visionz1 Glad to hear you got it fixed on your own, good job 👍

The bug was probably introduced with the jump from version 1.1 to 1.2 which changed faction tags to be capital letters, so that might have broken some things.
Anyhow, it's safe to re-add the other mods if you haven't done that yet,, as they only use the pirate faction.

Anyhow, I'll lock the post now, seeing as it's been resolved.
Have fun, I hope you're excited for the next update: It's going to add something **_very_** interesting :)
